// <auto-generated />
using System;
using Journaway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Journaway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OccupancyDbContext))]
    partial class OccupancyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.RoomAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TravelGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TravelGroupId");

                    b.HasIndex("TravellerId");

                    b.HasIndex("HotelId", "Date");

                    b.HasIndex("HotelId", "Date", "TravellerId")
                        .IsUnique();

                    b.HasIndex("HotelId", "RoomId", "Date");

                    b.HasIndex("HotelId", "TravelGroupId", "Date");

                    b.ToTable("room_assignments", (string)null);
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "RoomCode")
                        .IsUnique();

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.TravelGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedTravellerCount")
                        .HasColumnType("integer");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "GroupId")
                        .IsUnique();

                    b.ToTable("travel_groups", (string)null);
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.TravellerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TravelGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TravelGroupId", "Surname", "FirstName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("travellers", (string)null);
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.RoomAssignmentEntity", b =>
                {
                    b.HasOne("Journaway.Infrastructure.Persistence.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Journaway.Infrastructure.Persistence.Entities.TravelGroupEntity", "TravelGroup")
                        .WithMany()
                        .HasForeignKey("TravelGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Journaway.Infrastructure.Persistence.Entities.TravellerEntity", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("TravelGroup");

                    b.Navigation("Traveller");
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.TravellerEntity", b =>
                {
                    b.HasOne("Journaway.Infrastructure.Persistence.Entities.TravelGroupEntity", "TravelGroup")
                        .WithMany("Travellers")
                        .HasForeignKey("TravelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelGroup");
                });

            modelBuilder.Entity("Journaway.Infrastructure.Persistence.Entities.TravelGroupEntity", b =>
                {
                    b.Navigation("Travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
